version: "3.1"
services:
  my-api:
    build: ./src/MyApi
    ports: 
      - 80:80
    networks:
      - my-network
  my-nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports: 
      - 1935:1935
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  my-network: